# Python for Spatial Analysis
## Second part of the module of GG3209 Spatial Analysis with GIS.
### Notebook to practice NumPy and Pandas - Exercises

---
Dr Fernando Benitez -  University of St Andrews - School of Geography and Sustainable Development - First Iteration 2023 v.1.0 

# Practicing NumPy

## 2.0 
Import numpy under the alias `np`.

In [1]:
import numpy as np

## 2.1 

Create the following arrays:

* Create an array of 10 ones.

* Create an array of the integers 1 to 20.

* Create a 5 x 5 matrix of ones with a dtype int.

In [16]:
array=np.ones(10)
print(array)
array2=np.arange(1,21)
print(array2)
array3=np.ones((5,5), dtype="int8")
print(array3)


[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


## 2.2 
Use numpy to:
1. Create an 3D matrix of 3 x 3 x 3 full of random numbers drawn from a standard normal distribution (hint: `np.random.randn()`)
2. Reshape the above array into shape (27,)

In [20]:
array4 = np.random.random((3,3,3))
print(array4)
array4b=array4.reshape(27)
print(array4)

[[[0.19712106 0.82275005 0.13657237]
  [0.88633137 0.0391402  0.13524766]
  [0.24915003 0.80774345 0.42819003]]

 [[0.83277275 0.19459112 0.65194995]
  [0.63833279 0.02748032 0.90934177]
  [0.24196685 0.0793173  0.45837982]]

 [[0.5311043  0.31403962 0.16438312]
  [0.50517946 0.66829061 0.54536273]
  [0.44104263 0.67710178 0.59249162]]]
[[[0.19712106 0.82275005 0.13657237]
  [0.88633137 0.0391402  0.13524766]
  [0.24915003 0.80774345 0.42819003]]

 [[0.83277275 0.19459112 0.65194995]
  [0.63833279 0.02748032 0.90934177]
  [0.24196685 0.0793173  0.45837982]]

 [[0.5311043  0.31403962 0.16438312]
  [0.50517946 0.66829061 0.54536273]
  [0.44104263 0.67710178 0.59249162]]]


# 2.3 

Create an array of 20 linearly spaced numbers between 1 and 10.

In [21]:
array5=np.linspace(1,10,20)
print(array5)

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


## 2.4

Run the following code to create an array of shape 4 x 4 and then use indexing to produce the outputs shown below.

In [11]:
import numpy as np
array6= np.arange(1, 26).reshape(5, -1)
print(array6)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [30]:
print(array6[3,4])


20


20

In [59]:
print(array6[:,3:0:1])

[]


```python
array([[ 9, 10],
       [14, 15],
       [19, 20],
       [24, 25]])
```

In [36]:
print(array6[1])

[ 6  7  8  9 10]


```python
array([ 6,  7,  8,  9, 10])
```

In [ ]:
# Code comes here

## 2.5 

Calculate the sum of all the numbers in `a`.

In [64]:
sum([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25])

325

## 2.6 

Calculate the sum of each row in `a`.

In [9]:
row1=np.array([1,2,3,4,5])
print(np.sum(row1))
row2=np.array([6,7,8,9,10])
print(np.sum(row2))
row3=np.array([11,12,13,14,15])
print(np.sum(row3))
row4=np.sum([16,17,18,19,20])
print(np.sum(row4))
row5=np.array([21,22,23,24,25])
print(np.sum(row5))

15
40
65
90
115


## 2.7 

Extract all values of `a` greater than the mean of `a` (hint: use a boolean mask).

In [13]:
print(np.mean(array6))
#want to print all values greater than 13 
print(array6[array6 > 13])

13.0
[14 15 16 17 18 19 20 21 22 23 24 25]


# Practicing Pandas

## 2.8

In this set of practice exercises we'll be investigating the carbon footprint of different foods. 

We'll be leveraging a dataset compiled by [Kasia Kulma](https://r-tastic.co.uk/post/from-messy-to-tidy/) and contributed to [R's Tidy Tuesday project](https://github.com/rfordatascience/tidytuesday).

Start by importing pandas with the alias `pd`.

In [14]:
import pandas as pd

## 2.9 

The dataset we'll be working with has the following columns:

|column      |description |
|:-------------|:-----------|
|country       | Country Name |
|food_category | Food Category |
|consumption   | Consumption (kg/person/year) |
|co2_emmission | Co2 Emission (Kg CO2/person/year) |


Import the dataset as a dataframe named `df` from this url: <https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-18/food_consumption.csv>

In [15]:
df=pd.read_csv("data/food_consumption.csv", sep=",", header=0, encoding="ISO-8859-1")

## 2.10 

How many rows and columns are there in the dataframe?

In [16]:
print(len(df))
print(len(df.columns))

1430
4


## 2.11

What is the mean `co2_emission` of the whole dataset?

In [17]:
df2=df["co2_emmission"].mean()
print(df2)


74.383993006993


## 2.12

What is the maximum `co2_emmission` in the dataset and which food type and country does it belong to?

In [23]:
df3=df["co2_emmission"].max()
print(df3)
df["Max"] = df.groupby("food_category")['food_category'].max()
print(df["Max"])

1712.0
0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
       ... 
1425    NaN
1426    NaN
1427    NaN
1428    NaN
1429    NaN
Name: Max, Length: 1430, dtype: object


## 2.13

How many countries produce more than 1000 Kg CO2/person/year for at least one food type?

In [27]:
df2 = df.query('co2_emmission > 1000')
print(df2)
#5 countries 

       country food_category  consumption  co2_emmission  Max
2    Argentina          Beef        55.48        1712.00  NaN
13   Australia          Beef        33.86        1044.85  NaN
57         USA          Beef        36.24        1118.29  NaN
90      Brazil          Beef        39.25        1211.17  NaN
123    Bermuda          Beef        33.15        1022.94  NaN


## 2.14

Which country consumes the least amount of beef per person per year?


In [35]:
beefdf = df.query('food_category=="Beef"')
print(beefdf)
#Liberia 

           country food_category  consumption  co2_emmission  Max  \
2        Argentina          Beef        55.48        1712.00  NaN   
13       Australia          Beef        33.86        1044.85  NaN   
24         Albania          Beef        22.50         694.30  NaN   
35         Iceland          Beef        13.36         412.26  NaN   
46     New Zealand          Beef        22.49         693.99  NaN   
...            ...           ...          ...            ...  ...   
1377  Sierra Leone          Beef         1.99          61.41  NaN   
1388     Sri Lanka          Beef         1.38          42.58  NaN   
1399     Indonesia          Beef         2.59          79.92  NaN   
1410       Liberia          Beef         0.78          24.07  NaN   
1421    Bangladesh          Beef         1.28          39.50  NaN   

                          Min  
2     Nuts inc. Peanut Butter  
13                       Pork  
24                        NaN  
35                       Pork  
46         

## 2.15

What is the total emissions of all the meat products (Pork, Poultry, Fish, Lamb & Goat, Beef) in the dataset combined?

In [61]:
just_pork = df[df["food_category"]== "Pork"]
print(just_pork)
just_poultry = df[df["food_category"]== "Poultry"]
print(just_poultry)
just_fish = df[df["food_category"]== "Fish"]
just_lambgoat = df[df["food_category"]== "Lamb & Goat"]
just_beef = df[df["food_category"]== "Beef"]

           country food_category  consumption  co2_emmission  Max          Min
0        Argentina          Pork        10.51          37.20  NaN  Lamb & Goat
11       Australia          Pork        24.14          85.44  NaN          NaN
22         Albania          Pork        10.88          38.51  NaN          NaN
33         Iceland          Pork        21.69          76.77  NaN          NaN
44     New Zealand          Pork        22.29          78.90  NaN          NaN
...            ...           ...          ...            ...  ...          ...
1375  Sierra Leone          Pork         1.22           4.32  NaN          NaN
1386     Sri Lanka          Pork         0.05           0.18  NaN          NaN
1397     Indonesia          Pork         2.98          10.55  NaN          NaN
1408       Liberia          Pork         4.01          14.19  NaN          NaN
1419    Bangladesh          Pork         0.00           0.00  NaN          NaN

[130 rows x 6 columns]
           country food_cate

# 2.16 

What is the total emissions of all other (non-meat) products in the dataset combined?

In [ ]:
# code comes here

## Well done!

That's all from this week, if you have any questions, do not forget to ask the TAs for assistance.